# Generated by Django 2.2 on 2020-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Artist', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Beats_per_minute', models.IntegerField(default=0)),
                ('Danceability', models.IntegerField(default=0)),
                ('music_id', models.IntegerField(default=0)),
            ],
        ),
    ]
